################################################################
# Globals
################################################################

defaultEntryPoints = ["http"]

################################################################
# Entrypoints
################################################################

[entryPoints]
  [entryPoints.http]
  address = ":80"

################################################################
# Docker configuration backend
################################################################
[docker]
watch = true
exposedbydefault = false
